package migrations

import (
	"database/sql"

	"github.com/pressly/goose/v3"
)

func init() {
	goose.AddMigration(upInitExpences, downInitExpences)
}

func upInitExpences(tx *sql.Tx) error {
	const query = `
	CREATE TABLE expences 
	(
		id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		user_id bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
		category_id bigint NOT NULL REFERENCES expence_category (id) ON DELETE CASCADE,
		ts timestamp NOT NULL,
		total bigint NOT NULL
	);
	-- BTree индекс на user id и timestamp, так как именно эта связка используется для получения отчёта
	-- # 1 миллион записей - построение отчета: без индекса - 250мс, с индексом - 150мс
	CREATE INDEX ts_idx ON expences (user_id, ts) INCLUDE (total);
	`

	_, err := tx.Exec(query)

	return err
}

func downInitExpences(tx *sql.Tx) error {
	const query = `
	DROP INDEX ts_idx;
	DROP TABLE expences;
	`
	_, err := tx.Exec(query)
	return err
}
