// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/report.proto

package api

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Report struct {
	UserId               *wrappers.Int64Value `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Expences             []*Expence           `protobuf:"bytes,2,rep,name=expences,proto3" json:"expences,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_3897b7ab72282a4a, []int{0}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetUserId() *wrappers.Int64Value {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *Report) GetExpences() []*Expence {
	if m != nil {
		return m.Expences
	}
	return nil
}

type Expence struct {
	Id                   *wrappers.Int64Value  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId           *wrappers.Int64Value  `protobuf:"bytes,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName         *wrappers.StringValue `protobuf:"bytes,3,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	Ts                   *wrappers.Int64Value  `protobuf:"bytes,4,opt,name=ts,proto3" json:"ts,omitempty"`
	Total                *wrappers.Int64Value  `protobuf:"bytes,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Expence) Reset()         { *m = Expence{} }
func (m *Expence) String() string { return proto.CompactTextString(m) }
func (*Expence) ProtoMessage()    {}
func (*Expence) Descriptor() ([]byte, []int) {
	return fileDescriptor_3897b7ab72282a4a, []int{1}
}

func (m *Expence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expence.Unmarshal(m, b)
}
func (m *Expence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expence.Marshal(b, m, deterministic)
}
func (m *Expence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expence.Merge(m, src)
}
func (m *Expence) XXX_Size() int {
	return xxx_messageInfo_Expence.Size(m)
}
func (m *Expence) XXX_DiscardUnknown() {
	xxx_messageInfo_Expence.DiscardUnknown(m)
}

var xxx_messageInfo_Expence proto.InternalMessageInfo

func (m *Expence) GetId() *wrappers.Int64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Expence) GetCategoryId() *wrappers.Int64Value {
	if m != nil {
		return m.CategoryId
	}
	return nil
}

func (m *Expence) GetCategoryName() *wrappers.StringValue {
	if m != nil {
		return m.CategoryName
	}
	return nil
}

func (m *Expence) GetTs() *wrappers.Int64Value {
	if m != nil {
		return m.Ts
	}
	return nil
}

func (m *Expence) GetTotal() *wrappers.Int64Value {
	if m != nil {
		return m.Total
	}
	return nil
}

type ReportResponse struct {
	ResponseCode         *wrappers.Int64Value `protobuf:"bytes,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReportResponse) Reset()         { *m = ReportResponse{} }
func (m *ReportResponse) String() string { return proto.CompactTextString(m) }
func (*ReportResponse) ProtoMessage()    {}
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3897b7ab72282a4a, []int{2}
}

func (m *ReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportResponse.Unmarshal(m, b)
}
func (m *ReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportResponse.Marshal(b, m, deterministic)
}
func (m *ReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportResponse.Merge(m, src)
}
func (m *ReportResponse) XXX_Size() int {
	return xxx_messageInfo_ReportResponse.Size(m)
}
func (m *ReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportResponse proto.InternalMessageInfo

func (m *ReportResponse) GetResponseCode() *wrappers.Int64Value {
	if m != nil {
		return m.ResponseCode
	}
	return nil
}

func init() {
	proto.RegisterType((*Report)(nil), "proto_report.Report")
	proto.RegisterType((*Expence)(nil), "proto_report.Expence")
	proto.RegisterType((*ReportResponse)(nil), "proto_report.ReportResponse")
}

func init() { proto.RegisterFile("api/report.proto", fileDescriptor_3897b7ab72282a4a) }

var fileDescriptor_3897b7ab72282a4a = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x6b, 0xe2, 0x40,
	0x14, 0xc7, 0xd7, 0xb8, 0xea, 0xf2, 0xcc, 0x2e, 0xcb, 0xd0, 0x42, 0xb0, 0x52, 0x24, 0x27, 0x41,
	0x9c, 0x10, 0x2b, 0x3d, 0x15, 0x4a, 0x2d, 0x3d, 0x78, 0x29, 0x34, 0x42, 0x0f, 0xbd, 0xc8, 0xc4,
	0xbc, 0xa6, 0xc1, 0x38, 0x33, 0x9d, 0x19, 0xdb, 0xda, 0x2f, 0xd2, 0xaf, 0x5b, 0xcc, 0x18, 0xa9,
	0xb4, 0xa0, 0xa7, 0x3c, 0xfe, 0xf9, 0xfd, 0x5e, 0xfe, 0xe4, 0xc1, 0x7f, 0x26, 0xb3, 0x40, 0xa1,
	0x14, 0xca, 0x50, 0xa9, 0x84, 0x11, 0xc4, 0x2d, 0x1e, 0x53, 0x9b, 0xb5, 0x4e, 0x53, 0x21, 0xd2,
	0x1c, 0x83, 0x22, 0x8c, 0x97, 0x8f, 0xc1, 0xab, 0x62, 0x52, 0xa2, 0xd2, 0x96, 0xf6, 0x9f, 0xa1,
	0x1e, 0x15, 0x24, 0x19, 0x42, 0x63, 0xa9, 0x51, 0x4d, 0xb3, 0xc4, 0xab, 0x74, 0x2a, 0xdd, 0xe6,
	0xe0, 0x84, 0x5a, 0x97, 0x96, 0x2e, 0x1d, 0x73, 0x73, 0x3e, 0xbc, 0x67, 0xf9, 0x12, 0xa3, 0xfa,
	0x9a, 0x1d, 0x27, 0x24, 0x84, 0x3f, 0xf8, 0x26, 0x91, 0xcf, 0x50, 0x7b, 0x4e, 0xa7, 0xda, 0x6d,
	0x0e, 0x8e, 0xe9, 0xd7, 0x02, 0xf4, 0xc6, 0xbe, 0x8d, 0xb6, 0x98, 0xff, 0xe1, 0x40, 0x63, 0x93,
	0x92, 0x1e, 0x38, 0x87, 0x7d, 0xcf, 0xc9, 0x12, 0x72, 0x01, 0xcd, 0x19, 0x33, 0x98, 0x0a, 0xb5,
	0x5a, 0xb7, 0x74, 0xf6, 0x5b, 0x50, 0xf2, 0xe3, 0x84, 0x5c, 0xc1, 0xdf, 0xad, 0xcd, 0xd9, 0x02,
	0xbd, 0x6a, 0xe1, 0xb7, 0xbf, 0xf9, 0x13, 0xa3, 0x32, 0x9e, 0xda, 0x05, 0x6e, 0xa9, 0xdc, 0xb2,
	0x45, 0xd1, 0xd6, 0x68, 0xef, 0xf7, 0x01, 0x6d, 0x8d, 0x26, 0x21, 0xd4, 0x8c, 0x30, 0x2c, 0xf7,
	0x6a, 0xfb, 0x79, 0x4b, 0xfa, 0x77, 0xf0, 0xcf, 0x1e, 0x23, 0x42, 0x2d, 0x05, 0xd7, 0x48, 0x2e,
	0xc1, 0x55, 0x9b, 0xf9, 0x5a, 0x24, 0x78, 0xc8, 0x9f, 0xda, 0x11, 0x06, 0x11, 0xb8, 0x76, 0xe5,
	0x04, 0x79, 0x82, 0x8a, 0x8c, 0x00, 0xd6, 0xd3, 0xe6, 0xe6, 0x47, 0xbb, 0xb7, 0xb2, 0x69, 0xab,
	0xfd, 0x53, 0x5a, 0x56, 0xf2, 0x7f, 0x8d, 0xfa, 0x0f, 0xbd, 0x34, 0x33, 0x39, 0x8b, 0xa9, 0x78,
	0x17, 0x9c, 0x26, 0xf8, 0x12, 0xb0, 0xb9, 0xd0, 0xab, 0xf9, 0x53, 0x18, 0x0e, 0x03, 0x83, 0x39,
	0xa6, 0x8a, 0x2d, 0xfa, 0xb1, 0x30, 0x01, 0x93, 0x59, 0x5c, 0x2f, 0xb6, 0x9d, 0x7d, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x1d, 0x55, 0xb4, 0x4e, 0xab, 0x02, 0x00, 0x00,
}
